textures/WZ-imperial/SolidMetal_001
{
	warzoneEnabled
	qer_editorimage	textures/WZ-imperial/SolidMetal_001
	q3map_material      SolidMetal
	q3map_clipModel
	//tesselation
	//tesselationLevel 3.0
	//tesselationAlpha 1.0
	{
	map textures/WZ-imperial/SolidMetal_001
	blendfunc GL_ONE GL_ZERO
	depthWrite
	rgbGen identity
	}
}

textures/WZ-imperial/SolidMetal_002
{
	warzoneEnabled
	qer_editorimage	textures/WZ-imperial/SolidMetal_002
	q3map_material      SolidMetal
	q3map_clipModel
	//tesselation
	//tesselationLevel 3.0
	//tesselationAlpha 1.0
	{
	map textures/WZ-imperial/SolidMetal_002
	blendfunc GL_ONE GL_ZERO
	depthWrite
	rgbGen identity
	}
}

textures/WZ-imperial/SolidMetal_003
{
	warzoneEnabled
	qer_editorimage	textures/WZ-imperial/SolidMetal_003
	q3map_material      SolidMetal
	q3map_clipModel
	//tesselation
	//tesselationLevel 3.0
	//tesselationAlpha 1.0
	{
	map textures/WZ-imperial/SolidMetal_003
	blendfunc GL_ONE GL_ZERO
	depthWrite
	rgbGen identity
	}
}

textures/WZ-imperial/SolidMetal_004
{
	warzoneEnabled
	qer_editorimage	textures/WZ-imperial/SolidMetal_004
	q3map_material      SolidMetal
	q3map_clipModel
	//tesselation
	//tesselationLevel 3.0
	//tesselationAlpha 1.0
	{
	map textures/WZ-imperial/SolidMetal_004
	blendfunc GL_ONE GL_ZERO
	depthWrite
	rgbGen identity
	}
}

textures/WZ-imperial/SolidMetal_005
{
	warzoneEnabled
	qer_editorimage	textures/WZ-imperial/SolidMetal_005
	q3map_material      SolidMetal
	q3map_clipModel
	//tesselation
	//tesselationLevel 3.0
	//tesselationAlpha 1.0
	{
	map textures/WZ-imperial/SolidMetal_005
	blendfunc GL_ONE GL_ZERO
	depthWrite
	rgbGen identity
	}
}

textures/WZ-Imperial/WZ_SolidMetal_001
{
	warzoneEnabled
	inside
	qer_editorimage	textures/WZ-Imperial/WZ_SolidMetal_001
	q3map_material	tiles
	q3map_clipModel
	//tesselation
	//tesselationLevel 3.0
	//tesselationAlpha 1.0
	{
	map textures/WZ-Imperial/WZ_SolidMetal_001
	blendfunc GL_ONE GL_ZERO
	depthWrite
	rgbGen identity
  }
}

textures/WZ-Imperial/WZ_SolidMetal_002
{
	warzoneEnabled
	qer_editorimage	textures/WZ-Imperial/WZ_SolidMetal_002
	q3map_material	tiles
	q3map_clipModel
	//tesselation
	//tesselationLevel 3.0
	//tesselationAlpha 1.0
	{
	map textures/WZ-Imperial/WZ_SolidMetal_002
	blendfunc GL_ONE GL_ZERO
	depthWrite
	rgbGen identity
  }
}

textures/WZ-Imperial/WZ_SolidMetal_003
{
	warzoneEnabled
	qer_editorimage	textures/WZ-Imperial/WZ_SolidMetal_003
	q3map_material	tiles
	q3map_clipModel
	//tesselation
	//tesselationLevel 3.0
	//tesselationAlpha 1.0
	{
	map textures/WZ-Imperial/WZ_SolidMetal_003
	blendfunc GL_ONE GL_ZERO
	depthWrite
	rgbGen identity
  }
}

textures/WZ-Imperial/WZ_SolidMetal_004
{
	warzoneEnabled
	qer_editorimage	textures/WZ-Imperial/WZ_SolidMetal_004
	q3map_material	solidmetal
	q3map_clipModel
	//tesselation
	//tesselationLevel 3.0
	//tesselationAlpha 1.0
	{
	map textures/WZ-Imperial/WZ_SolidMetal_004
	blendfunc GL_ONE GL_ZERO
	depthWrite
	rgbGen identity
  }
}

textures/WZ-Imperial/Light-Imp1
{
	warzoneEnabled
	qer_editorimage	textures/WZ-Imperial/Light-Imp1
	q3map_material	tiles
	q3map_clipModel
	//glowStrength 1.0
	//glowVibrancy 1.0
	//emissiveHeightScale 1.0
	emissiveRadiusscale 100.0 
	emissiveColorScale 4.0
	tesselation
	tesselationLevel 1.0
	tesselationAlpha 1.0
	{
	map textures/WZ-Imperial/Light-Imp1
	blendfunc GL_ONE GL_ZERO
	depthWrite
	rgbGen identity
  }
}

textures/WZ-Imperial/Light-Imp2
{
	warzoneEnabled
	qer_editorimage	textures/WZ-Imperial/Light-Imp2
	q3map_material	tiles
	q3map_clipModel
	glowStrength 1.0
	glowVibrancy 1.0
	//emissiveHeightScale 1.0
	emissiveColorScale 2.0
	emissiveRadius 16.0
	//tesselation
	//tesselationLevel 1.0
	//tesselationAlpha 1.0
	{
	map textures/WZ-Imperial/Light-Imp2
	blendfunc GL_ONE GL_ZERO
	depthWrite
	rgbGen identity
  }
}

textures/WZ-Imperial/Light-Imp3
{
	warzoneEnabled
	qer_editorimage	textures/WZ-Imperial/Light-Imp3
	q3map_material	solidmetal
	q3map_clipModel
	glowStrength 1.0
	glowVibrancy 1.0
	emissiveColorScale 1.0
	emissiveHeightScale 1.0
	emissiveColorScale 1.0
	emissiveRadius 100.0 
	tesselation
	tesselationLevel 1.0
	tesselationAlpha 1.0
	{
	map textures/WZ-Imperial/Light-Imp3
	blendfunc GL_ONE GL_ZERO
	depthWrite
	rgbGen identity
  }
}

